fix: fix execute_shell_command for rpicam edge case
Sometimes the `rpicam-hello --list-cameras` can throw an error but will
still print the cameras:
```sh
Available cameras
-----------------
0 : imx219 [3280x2464 10-bit RGGB] (/base/soc/i2c0mux/i2c@1/imx219@10)
    Modes: 'SRGGB10_CSI2P' : 640x480 [206.65 fps - (1000, 752)/1280x960
crop]
                             1640x1232 [41.85 fps - (0, 0)/3280x2464
crop]
                             1920x1080 [47.57 fps - (680, 692)/1920x1080
crop]
                             3280x2464 [21.19 fps - (0, 0)/3280x2464
crop]
           'SRGGB8' : 640x480 [206.65 fps - (1000, 752)/1280x960 crop]
                      1640x1232 [83.70 fps - (0, 0)/3280x2464 crop]
                      1920x1080 [47.57 fps - (680, 692)/1920x1080 crop]
                      3280x2464 [21.19 fps - (0, 0)/3280x2464 crop]

ERROR:  failed to generate capture configuration
```
This results in a non zero exit code and therefore `check_output` would
result in a `CalledProcessError`.

This will fix the issue for this edge case but keeps the same behavior
for other `execute_shell_command` calls.

Signed-off-by: Patrick Gehrsitz <github@mryel.de>